include:
- remote: 'https://raw.githubusercontent.com/geekplus-cn/athena-ci/master/jobs/build.yml'
- remote: 'https://raw.githubusercontent.com/geekplus-cn/athena-ci/master/jobs/test.yml'

variables:
  BUILD_SHELL: 'mvn clean package  -DskipTests'  ##构建命令
  CACHE_DIR: 'target/'
  TEST_SHELL : 'mvn test'                                   ##测试命令
  JUNIT_REPORT_PATH: 'target/surefire-reports/TEST-*.xml'   ##单元测试报告
  
stages:
- build
- test

maven-build:
  stage: build
  extends: .build
  rules:
  - when: on_success

unit-test:
  stage: test
  extends: .test
  scripts:
  - cd app-api
  - ls
  - $TEST_SHELL
  rules:
    - when: on_success
